In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial import distance_matrix
from numpy.random import seed
from numpy.random import randint
import random
from math import sqrt
import string
import sys

### Read CSV
##### Input: filename

In [2]:
def read_file(name):
    df = pd.read_csv('../data/'+name);
    # node names array
    namesArr = df.columns.values
    # nodes dictionary
    dict = {}
    for i in range(0, df.columns.size):
        dict[df.columns[i]] = i;
    return namesArr, dict, df.values

### Generate n nodes
##### Input: n (number of nodes), lim - space limit

In [3]:
def generate_n_nodes(n,lim):
    # Nodes position (x,y)
    seed(1)
    coord = []
    xList = []
    yList = []
    for i in range(0, n):
        x = randint(0, lim)
        xList.append(x)
        y = randint(0, lim)
        yList.append(y)
        coord.append((x,y))
    mx = float('-inf')
    for x,y in coord:
        if x > mx:
            mx = x
        if y > mx:
            mx = y
    # Nodes Dictionary
    dict = {}
    alphabet_string = string.ascii_uppercase
    alphabet_list = list(alphabet_string)
    alphabet_list = alphabet_list[:n]
    for i, txt in enumerate(alphabet_list):
        dict[txt] = i;
    # Distances matrix 
    tempList = []
    for x,y in coord:
        for i,j in coord :
            tempList.append(round(sqrt(pow((x-i),2) + pow((y-j),2) ),1))
    mat = []
    while tempList != []:
      mat.append(tempList[:n])
      tempList = tempList[n:]
    dist_mat = pd.DataFrame(mat)
    return coord, dict, dist_mat


### Objective Function
##### Input: nodes names array, nodes dictionary, distances matrix, individual array

In [4]:
def objective_function(namesArr,d, dMatrix, sol):
    if sol[0] != sol[len(sol)-1]: return -1 #the fist and last character must be the same
    rep = sol.rstrip(sol[-1])
    if not len(set(rep)) == len(rep): return -1 # the nodes aren't repeated
    if sorted(rep) != sorted(namesArr): return -1 # all the nodes are included in the solution
    
    n = len(namesArr)
    w = 0;
    for i in range(0, n):
            w+=dMatrix[ord(sol[i])-65][ord(sol[i+1])-65]
    return w
 

In [5]:
# MAIN
print("\n--------------------------------- 1. Read the source file ------------------------------------------------")
print("\t~~~~ Nodes names array ~~~~ ")
print(read_file("adjacency_matrix.csv")[0])
print("\t~~~~ Nodes dictionary ~~~~ ")
print(read_file("adjacency_matrix.csv")[1])
print("\~~~~ Distances Matrix ~~~~ ")
print(read_file("adjacency_matrix.csv")[2])
print("\n--------------------------------- 2. Generate n nodes ------------------------------------------------")
print("\t~~~~ Nodes position (x,y) ~~~~ ")
n = int(input("-> # nodes: "))
lim = int(input("-> lim: "))
print(generate_n_nodes(n,lim)[0] )
print("\t~~~~ Nodes dictionary ~~~~ ")
print(generate_n_nodes(n,lim)[1] )
print("\t~~~~ Distances Matrix ~~~~ ")
print(generate_n_nodes(n,lim)[2] )
print("\n--------------------------------- 3. Objective function ------------------------------------------------")
namesArr = read_file("adjacency_matrix.csv")[0]
dictionary = read_file("adjacency_matrix.csv")[1]
matrix = read_file("adjacency_matrix.csv")[2]
print("weight: ",objective_function(namesArr, dictionary, matrix, input("solution: ")))



--------------------------------- 1. Read the source file ------------------------------------------------
	~~~~ Nodes names array ~~~~ 
['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J']
	~~~~ Nodes dictionary ~~~~ 
{'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6, 'H': 7, 'I': 8, 'J': 9}
\~~~~ Distances Matrix ~~~~ 
[[ 0 59 48 69 54 91 55 34 81 72]
 [59  0 45 19 45 73 48 13 13 42]
 [48 45  0 97 11 65 12 58 70 45]
 [69 19 97  0 31 94 23 66 71 13]
 [54 45 11 31  0 95 37 47 24 49]
 [91 73 65 94 95  0 62 35 38 61]
 [55 48 12 23 37 62  0 82 96 47]
 [34 13 58 66 47 35 82  0 10 47]
 [81 13 70 71 24 38 96 10  0 63]
 [72 42 45 13 49 61 47 47 63  0]]

--------------------------------- 2. Generate n nodes ------------------------------------------------
	~~~~ Nodes position (x,y) ~~~~ 
-> # nodes: 3
-> lim: 10
[(5, 8), (9, 5), (0, 0)]
	~~~~ Nodes dictionary ~~~~ 
{'A': 0, 'B': 1, 'C': 2}
	~~~~ Distances Matrix ~~~~ 
     0     1     2
0  0.0   5.0   9.4
1  5.0   0.0  10.3
2  9.4  10.3   0.0

---

# Genetic Algorithm

In [20]:
n = 3
def permutations(remaining, candidate=''):
    if n == 0: return
    if len(remaining) == 0:
        print(candidate)
    for i in range(len(remaining)):
        newCandidate = candidate + remaining[i]
        newRemaining = remaining[0:i] + remaining[i+1:]
        permutations(newRemaining, newCandidate)
        
permutations("ABC")

ABC
ACB
BAC
BCA
CAB
CBA


In [7]:
#def roulette_selection():

In [8]:
def crossover(parents, pr): # pr = probability of reproduction
    for i in range(len(parents)):
        if(random.uniform(0, 1) < pr)
            
        

SyntaxError: invalid syntax (Temp/ipykernel_7444/913097659.py, line 3)

In [21]:
def genetic_algorithm(n, g, pr, pm):
    #create the initial population
    generate_n_nodes(n, lim) 
    #calculate the population fitness
    print( generate_n_nodes(n, lim)[2],"\n")
    namesArr = (generate_n_nodes(n, lim)[1]).keys()
    dictionary = generate_n_nodes(n, lim)[1]
    matrix = generate_n_nodes(n, lim)[2]
    parents = input("solution: ")
    elite = objective_function(namesArr, dictionary, matrix, parents)
    print("weight: ",elite)
    while g > 0: # While the number of generations is less than G or we haven’t found a good solution
        crossover(parents, pr)
        break
    
lim = 100
n = 3 # population size
g = 3 # max number of generations
pr = 0.8 # reproduction's probability
pm = 0.8 # mutation probability

genetic_algorithm(n,g,pr,pm)

NameError: name 'generate_n_nodes' is not defined