In [1]:
import numpy as np
from scipy.optimize import linprog
from particle_swarm_optimization import particle_swarm_optimization

# Linear programming problems

## Problem I

### Description

Un herrero con 80 Kg. de acero y 120 Kg. de aluminio quiere hacer bicicletas de paseo y de montaña que
quiere vender, respectivamente a 20.000 y 15.000 pesos cada una para sacar el máximo beneficio. Para la de
paseo empleará 1 kg de acero y 3 kg de aluminio, y para la de montaña 2 kg de ambos metales. ¿Cuántas
bicicletas de paseo y de montaña deberá fabricar para maximizar las utilidades?

### Model

$$ Max(20000p + 15000m) $$

$$ Min(-(20000p + 15000m)) $$

#### Sujeto a

$$ 1p + 2m <= 80 $$

$$ 3p + 2m <= 120 $$

$$ p >= 0 $$

$$ m >= 0 $$

#### Donde 

*m*: Numero de bicicletas de montana.

*p*: Numero de bicicletas de paseo.

### Solution

#### Scipy's linprog

In [2]:
A = [[1, 2], [3, 2]]
b = [80, 120]
bounds = [[0, None], [0, None]]
c = [-20000, -15000]

linprog(c, A_ub = A, b_ub = b, bounds = bounds)

           con: array([], dtype=float64)
 crossover_nit: 0
         eqlin:  marginals: array([], dtype=float64)
  residual: array([], dtype=float64)
           fun: -850000.0
       ineqlin:  marginals: array([-1250., -6250.])
  residual: array([0., 0.])
         lower:  marginals: array([0., 0.])
  residual: array([20., 30.])
       message: 'Optimization terminated successfully. (HiGHS Status 7: Optimal)'
           nit: 2
         slack: array([0., 0.])
        status: 0
       success: True
         upper:  marginals: array([0., 0.])
  residual: array([inf, inf])
             x: array([20., 30.])

#### Our particle swarm

In [3]:
def ob(x):
    p, m = x
    return -(20000*p + 15000*m)
def isFeasible(x) -> bool:
    p, m = x
    if p < 0 or m < 0: return False
    if p + 2*m > 80: return False
    if 3*p + 2*m > 120: return False
    return True
b = [[0, 50], [0, 50]]
particle_swarm_optimization(ob, isFeasible, b)

[[18.49370329  9.51123169]
 [25.71343683  2.57571907]
 [34.38072473  1.87349163]
 [ 6.92574952 12.09663047]
 [20.41741913  5.21140728]
 [25.79565014  8.02692663]
 [ 9.44106229  2.00252961]
 [ 2.70762583 10.96335281]
 [25.01798748  8.24589439]
 [11.83325718 22.08847694]
 [ 4.07733388 29.91422438]
 [16.72166534 21.65124188]
 [12.46019408 18.16941913]
 [23.95664793 15.03919215]
 [27.42342181  3.28850931]
 [23.29993939 13.04422857]
 [24.93013181  2.96627287]
 [ 2.20720469 25.63012357]
 [24.24323357  3.2817798 ]
 [ 0.71101443 26.19111054]
 [13.01884123 18.47066481]
 [ 5.2819924  35.10779507]
 [18.74006293  3.13895434]
 [ 9.01839677  9.59261454]
 [21.87134596 14.84142164]]
[-512542.54108845 -552904.52260631 -715716.8690125  -319964.44747507
 -486519.4917936  -636316.90239245 -218859.18990087 -218602.80867324
 -624048.16545064 -567992.29763531 -530260.04332565 -659201.93488069
 -521745.16849958 -704720.84089716 -597796.07598509 -661662.21640045
 -543096.72913559 -428595.94739747 -534091.36833

{'sol': array([20.84735853, 28.7289622 ]), 'func': -847881.6036740454}

## Problem II

### Description

Una compañía fabrica y venden dos modelos de lámpara L1 y L2. Para su fabricación se necesita un trabajo
manual de 20 minutos para el modelo L1 y de 30 minutos para el L2; y un trabajo de máquina de 10 minutos para
L1 y de 10 minutos para L2. Se dispone para el trabajo manual de 100 horas al mes y para la máquina 80 horas
al mes. Sabiendo que el beneficio por unidad es de 15 y 10 euros para L1 y L2, respectivamente, planificar la
producción para obtener el máximo beneficio.

### Model

$$ Max(15L_1 + 10L_2) $$

$$ Min(-(15L_1 + 10L_2)) $$

#### Sujeto a

$$ 20L_1 + 30L_2 <= 100*60 $$

$$ 10L_1 + 10L_2 <= 80*60 $$

$$ L_1 >= 0 $$

$$ L_2 >= 0 $$

#### Donde 

*L_1*: Numero de lamparas tipo uno.

*L_2*: Numero de lamparas tipo dos.

### Solution

#### Scipy's linprog

In [4]:
A = [[20, 30], [10, 10]]
b = [100*60, 80*60]
bounds = [[0, None], [0, None]]
c = [-15, -10]

linprog(c, A_ub = A, b_ub = b, bounds = bounds)

           con: array([], dtype=float64)
 crossover_nit: 0
         eqlin:  marginals: array([], dtype=float64)
  residual: array([], dtype=float64)
           fun: -4500.0
       ineqlin:  marginals: array([-0.75, -0.  ])
  residual: array([   0., 1800.])
         lower:  marginals: array([ 0. , 12.5])
  residual: array([300.,   0.])
       message: 'Optimization terminated successfully. (HiGHS Status 7: Optimal)'
           nit: 2
         slack: array([   0., 1800.])
        status: 0
       success: True
         upper:  marginals: array([0., 0.])
  residual: array([inf, inf])
             x: array([300.,   0.])

#### Our particle swarm

In [5]:
def ob(x):
    lOne, lTwo = x
    return -(15*lOne + 10*lTwo)
def isFeasible(x) -> bool:
    lOne, lTwo = x
    if lOne < 0 or lTwo < 0: return False
    if 20*lOne + 30*lTwo > 100*60: return False
    if 10*lOne + 10*lTwo > 80*60: return False
    return True
b = [[0, 500], [0, 500]]
particle_swarm_optimization(ob, isFeasible, b)

[[165.0682873    1.9864993 ]
 [ 31.43242574  33.24084819]
 [133.39923358  65.36427814]
 [ 83.37047375  77.27672866]
 [191.15403534  11.49282288]
 [177.13578986  32.4016326 ]
 [ 26.56317148  97.55067976]
 [210.34758511  23.55643325]
 [158.01995989  65.83688332]
 [ 51.60031379 145.68278202]
 [ 35.02544698 102.09080135]
 [ 87.58631862  79.75284978]
 [ 91.28549657 106.86693172]
 [260.06489408  15.56936231]
 [ 20.0795472   74.62264547]
 [133.01420569 103.55243202]
 [ 97.42943427 102.26618746]
 [ 23.70949193  67.78816484]
 [191.89370644  32.77749419]
 [174.15946277   4.13519252]
 [175.08556338  21.46663064]
 [182.20783497  75.32369768]
 [ 60.79746098 118.56099673]
 [178.96271206  52.76207153]
 [221.94962354   2.2269505 ]]
[-2495.88930243  -803.89486808 -2654.63128513 -2023.32439284
 -2982.23875887 -2981.05317392 -1373.95436976 -3390.77810912
 -3028.66823159 -2230.83252701 -1546.28971821 -2111.32327713
 -2437.95176566 -4056.66703422 -1047.41966269 -3030.73740556
 -2484.10338872 -1033.52402736

{'sol': array([2.99999999e+02, 7.26242058e-07]), 'func': -4499.999990921974}

## Problem III

### Description

En una granja de pollos se da una dieta, para engordar, con una composición mínima de 15 unidades de una
sustancia A y otras 15 de una sustancia B. En el mercado sólo se encuentra dos clases de compuestos: el tipo X
con una composición de una unidad de A y 5 de B, y el otro tipo, Y, con una composición de cinco unidades de A
y una de B. El precio del tipo X es de 10 euros y del tipo Y es de 30 €. ¿Qué cantidades se han de comprar de
cada tipo para cubrir las necesidades con un coste mínimo?

### Model

$$ Min(10x + 30y) $$

#### Sujeto a 

$$ -(x + 5y) <= -15 $$

$$ -(5x + y) <= -15 $$

$$ x >= 0 $$

$$ y >= 0 $$

#### Donde

*x*: Numero de tipos x

*y*: Numero de tipos y

### Solution

#### Scipy's linprog

In [6]:
A = [[-1, -5], [-5, -1]]
b = [-15, -15]
bounds = [[0, None], [0, None]]
c = [10, 30]

linprog(c, A_ub = A, b_ub = b, bounds = bounds)

           con: array([], dtype=float64)
 crossover_nit: 0
         eqlin:  marginals: array([], dtype=float64)
  residual: array([], dtype=float64)
           fun: 100.0
       ineqlin:  marginals: array([-5.83333333, -0.83333333])
  residual: array([0., 0.])
         lower:  marginals: array([0., 0.])
  residual: array([2.5, 2.5])
       message: 'Optimization terminated successfully. (HiGHS Status 7: Optimal)'
           nit: 2
         slack: array([0., 0.])
        status: 0
       success: True
         upper:  marginals: array([0., 0.])
  residual: array([inf, inf])
             x: array([2.5, 2.5])

#### Our particle swarm

In [7]:
def ob(sol):
    x, y = sol
    return (10*x + 30*y)
def isFeasible(sol) -> bool:
    x, y = sol
    if x < 0 or y < 0: return False
    if -(x + 5*y) > -15: return False
    if -(5*x + y) > -15: return False
    return True
b = [[0, 5], [0, 5]]
particle_swarm_optimization(ob, isFeasible, b)


[[2.69062927 4.96548075]
 [4.69933076 2.62142361]
 [4.92665264 3.6465468 ]
 [3.4298209  4.94585197]
 [2.27198274 3.69094755]
 [3.7204587  3.38342307]
 [4.80402667 2.56332348]
 [4.77359313 2.59254494]
 [2.7083473  3.23056969]
 [3.07872532 3.0309745 ]
 [2.52507515 4.34402487]
 [4.42073401 3.29968411]
 [4.78269716 2.42990016]
 [4.88561684 4.68215363]
 [2.73317507 4.0221184 ]
 [3.73101039 4.87378578]
 [4.21506413 3.06350099]
 [2.45175016 3.80509487]
 [2.56854199 3.30938734]
 [2.49601999 4.84953664]
 [4.9861873  4.01540381]
 [3.38016668 2.4633809 ]
 [3.58178663 4.08716405]
 [4.50034817 2.21510685]
 [4.5545196  4.62575283]]
[175.87071502 125.63601591 158.66293029 182.67376814 133.4482539
 138.70727926 124.93997119 125.51227944 124.0005636  121.71648825
 155.57149765 143.19786333 120.72397628 189.32077733 147.99530283
 183.52367719 134.05567104 138.67034765 124.96704027 170.44629899
 170.32398722 107.7030937  158.43278773 111.45668719 184.31778092]
21
0.5
0.755
0.8825000000000001
0.94625
0.97

{'sol': array([2.49999998, 2.50000012]), 'func': 100.00000342350293}

## Problem IV

### Description

Con el comienzo del curso se va a lanzar unas ofertas de material escolar. Unos almacenes quieren ofrecer
600 cuadernos, 500 carpetas y 400 bolígrafos para la oferta, empaquetándolo de dos formas distintas; en el
primer bloque pondrá 2 cuadernos, 1 carpeta y 2 bolígrafos; en el segundo, pondrán 3 cuadernos, 1 carpeta y 1
bolígrafo. Los precios de cada paquete serán 6.5 y 7 €, respectivamente. ¿Cuántos paquetes le convienen poner
de cada tipo para obtener el máximo beneficio?

### Model

$$ Max(6.5A + 7B) $$

$$ Min(-(6.5A + 7B)) $$

#### Sujeto a 

$$ 2A + 3B <= 600 $$

$$ A + B <= 500 $$

$$ 2A + B <= 400 $$

$$ A >= 0 $$

$$ B >= 0 $$

#### Donde

*A*: Numero de bloques uno

*B*: Numero de bloques dos

### Solution

#### Scipy's linprog

In [8]:
A = [[2, 3], [1, 1], [2, 1]]
b = [600, 500, 400]
bounds = [[0, None], [0, None]]
c = [-6.5, -7]

linprog(c, A_ub = A, b_ub = b, bounds = bounds)

           con: array([], dtype=float64)
 crossover_nit: 0
         eqlin:  marginals: array([], dtype=float64)
  residual: array([], dtype=float64)
           fun: -1675.0
       ineqlin:  marginals: array([-1.875, -0.   , -1.375])
  residual: array([  0., 250.,   0.])
         lower:  marginals: array([0., 0.])
  residual: array([150., 100.])
       message: 'Optimization terminated successfully. (HiGHS Status 7: Optimal)'
           nit: 2
         slack: array([  0., 250.,   0.])
        status: 0
       success: True
         upper:  marginals: array([0., 0.])
  residual: array([inf, inf])
             x: array([150., 100.])

#### Our particle swarm

In [9]:
def ob(sol):
    a, b = sol
    return -(6.5*a + 7*b)
def isFeasible(sol) -> bool:
    a, b = sol
    if a < 0 or b < 0: return False
    if (2*a + 3*b) > 600: return False
    if (a + b) > 500: return False
    if (2*a + b) > 400: return False
    return True
b = [[0, 250], [0, 250]]
particle_swarm_optimization(ob, isFeasible, b)


[[5.16102120e+01 1.33825498e+02]
 [9.29952015e+01 5.08815462e+01]
 [7.67199657e+00 7.48704783e+01]
 [1.55996593e+02 1.74627157e-01]
 [8.38118065e+01 9.46099392e+00]
 [1.31418588e+02 2.38374568e+01]
 [1.05012546e+02 7.91478080e+01]
 [6.43941981e+00 6.46026242e+01]
 [1.33687434e+02 4.10789259e+01]
 [1.46493549e+02 7.24801873e+01]
 [6.13188363e+00 5.93630042e+01]
 [7.47829594e+00 1.17924869e+01]
 [1.26264033e+02 1.95775671e+01]
 [1.20819509e+02 1.52118243e+01]
 [2.01243214e+01 7.07200664e+01]
 [5.44363440e+00 8.89243313e+01]
 [1.65921780e+02 5.15000670e+01]
 [9.39122172e+01 5.27807395e+01]
 [1.38139787e+02 8.13497242e+01]
 [6.28227679e+01 1.36266877e+02]
 [4.32811313e+01 6.74882682e+01]
 [1.01561540e+02 1.12425923e+02]
 [1.24145526e+02 9.31309895e+01]
 [2.22593645e+00 1.26291328e+02]
 [5.62927568e+00 1.94034697e+02]]
[-1272.24486339  -960.63963329  -573.96132573 -1015.2002449
  -611.00369985 -1021.0830163  -1236.61620368  -494.0745984
 -1156.52080095 -1459.5693808   -455.39827262  -131.15

{'sol': array([149.99999603, 100.00000265]), 'func': -1674.9999927178906}

## Problem V

### Description

Una escuela prepara una excursión para 400 alumnos. La empresa de transporte tiene 8 autobuses de 40
plazas y 10 de 50 plazas, pero sólo dispone de 9 conductores. El alquiler de un autocar grande cuesta 800 € y el
de uno pequeño 600 €. Calcular cuántos autobuses de cada tipo hay que utilizar para que la excursión resulte lo
más económica posible para la escuela.

### Model

$$ Min(600A + 800B) $$

#### Sujeto a

$$ -(40A + 50B) <= -400 $$

$$ A + B <= 9 $$

$$ 0 <= A <= 8 $$

$$ 0 <= B <= 10 $$

#### Donde

*A*: Numero de autobuses chicos.

*B*: Numero de autobuses grandes.

### Solution

#### Scipy's linprog

In [10]:
A = [[-40, -50], [1, 1]]
b = [-400, 9]
bounds = [[0, 8], [0, 10]]
c = [600, 800]

linprog(c, A_ub = A, b_ub = b, bounds = bounds)

           con: array([], dtype=float64)
 crossover_nit: 0
         eqlin:  marginals: array([], dtype=float64)
  residual: array([], dtype=float64)
           fun: 6200.0
       ineqlin:  marginals: array([ -20., -200.])
  residual: array([0., 0.])
         lower:  marginals: array([0., 0.])
  residual: array([5., 4.])
       message: 'Optimization terminated successfully. (HiGHS Status 7: Optimal)'
           nit: 0
         slack: array([0., 0.])
        status: 0
       success: True
         upper:  marginals: array([0., 0.])
  residual: array([3., 6.])
             x: array([5., 4.])

#### Our particle swarm

In [11]:
def ob(sol):
    a, b = sol
    return 600*a + 800*b
def isFeasible(sol) -> bool:
    a, b = sol
    if a < 0 or a > 8 or b < 0 or b > 10: return False
    if -(40*a + 50*b) > -400: return False
    if (a + b) > 9: return False
    return True
b = [[0, 10], [0, 10]]
particle_swarm_optimization(ob, isFeasible, b)

[[3.73137787 5.2615707 ]
 [4.17187575 4.79015301]
 [0.19201724 8.04787603]
 [1.8684323  6.54474841]
 [1.87142775 6.58928077]
 [0.62522869 8.17554526]
 [1.95356465 6.56918449]
 [0.66287147 8.32404527]
 [1.30436887 7.46876039]
 [0.73566285 7.8407296 ]
 [3.59232526 5.40175153]
 [2.00011337 6.8612564 ]
 [1.4105404  7.14709487]
 [1.87399461 6.72111381]
 [2.768326   5.80209648]
 [1.22738744 7.33652934]
 [2.39488953 6.28176826]
 [2.94074069 5.98326134]
 [1.74277718 6.88615121]
 [0.42590957 7.79923287]
 [0.05174745 8.68002772]
 [0.72083337 7.59464313]
 [0.59931546 7.58281367]
 [1.21476513 7.59968719]
 [0.45752773 7.7913261 ]]
[6448.08328649 6335.24785752 6553.5111644  6356.85810334 6394.2812666
 6915.5734262  6427.48638253 7056.95910109 6757.6296372  6713.98139256
 6476.79637607 6689.07314422 6564.00013046 6501.28781557 6302.672782
 6605.65593514 6462.3483241  6551.05348717 6554.58727756 6494.93203684
 6975.07064073 6508.21452294 6425.84021354 6808.60882485 6507.57752123]
14
0.5
0.755
0.6275
0

{'sol': array([4.51020407, 4.39183674]), 'func': 6219.591837092106}