# Workforce Scheduler

### Authors

Sara Carolina Gomez Delgado

Luis Eduardo Robles Jimenez

In [1]:
from data import * 
from genetic_algorithm import genetic_algorithm
import matplotlib.pyplot as plt
import numpy as np

In [2]:
def graph(points, lbl = None):
    if lbl is None: plt.scatter(np.arange(len(points)), points)
    else:
        plt.scatter(np.arange(len(points)), points, label = lbl)
        plt.legend()

In [3]:
popSize = 300

descanso = np.where(breaks == "Descansa")[0]
manana = np.where(breaks == "Mañana")[0]
tarde = np.where(breaks == "Tarde")[0]
comida = np.where(breaks == "Comida")[0]

In [4]:
pop = [[comida, manana, manana, comida, comida, comida, descanso] if p in domingos else [descanso, manana if np.random.random() <= 0.5 else tarde, comida, comida, comida, comida, comida] for p in people]
initial_population = [np.copy(pop) for i in range(popSize)]
initial_population = np.array(initial_population).reshape((popSize, len(people), 7))
initial_population.shape

(300, 18, 7)

In [5]:
r = genetic_algorithm(rules, (breaks, areas, inventario, people, domingos), popSize, 1000, pRep = 0.5, pMut = 0.5, dim = (len(people), 7, 0, len(breaks)), init = initial_population, debug = False)
r

{'solution': array([[0, 0, 0, 3, 0, 1, 0],
        [0, 0, 0, 1, 3, 0, 0],
        [0, 0, 2, 0, 1, 0, 0],
        [0, 0, 0, 2, 0, 1, 0],
        [1, 0, 2, 0, 0, 0, 0],
        [3, 0, 0, 0, 1, 0, 0],
        [2, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 2, 2, 0, 1],
        [0, 0, 0, 2, 0, 2, 1],
        [0, 0, 0, 3, 0, 1, 0],
        [0, 0, 1, 0, 0, 2, 0],
        [1, 0, 0, 2, 0, 0, 0],
        [1, 0, 0, 0, 0, 3, 0],
        [0, 1, 0, 0, 0, 3, 0],
        [0, 2, 2, 0, 0, 0, 1],
        [0, 2, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 2, 2, 1],
        [3, 0, 0, 0, 1, 0, 0]], dtype=int64),
 'fitness': 6,
 'callsToFunction': 300300,
 'bestTracker': [-26,
  -15,
  -6,
  -5,
  -5,
  -5,
  -5,
  -5,
  -5,
  -5,
  -5,
  -5,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
  -3,
 

In [6]:
a = rules(r['solution'], breaks, areas, inventario, people, domingos, True)
print(a[0])
print("{} errors.".format(len(a[1])))
print(*a[1][:10], sep = '\n')

[[0 0 0 3 0 1 0]
 [0 0 0 1 3 0 0]
 [0 0 2 0 1 0 0]
 [0 0 0 2 0 1 0]
 [1 0 2 0 0 0 0]
 [3 0 0 0 1 0 0]
 [2 1 0 0 0 0 0]
 [0 0 0 2 2 0 1]
 [0 0 0 2 0 2 1]
 [0 0 0 3 0 1 0]
 [0 0 1 0 0 2 0]
 [1 0 0 2 0 0 0]
 [1 0 0 0 0 3 0]
 [0 1 0 0 0 3 0]
 [0 2 2 0 0 0 1]
 [0 2 0 0 0 1 0]
 [0 0 0 0 2 2 1]
 [3 0 0 0 1 0 0]]
6
1 errors.
Nancy quiere el viernes


In [7]:
print("Nombre", "LUN", "MAR", "MIER", "JUE", "VIE", "SAB", "DOM", sep = "\t")
for i, p in enumerate(r['solution']):
    print(people[i][:6], end = '\t')
    for j, d in enumerate(p):
        print(codigos[d], end = '\t')
    print()

Nombre	LUN	MAR	MIER	JUE	VIE	SAB	DOM
Samant	C	C	C	T	C	D	C	
Luz	C	C	C	D	T	C	C	
Laura	C	C	M	C	D	C	C	
Maira	C	C	C	M	C	D	C	
Gloria	D	C	M	C	C	C	C	
Fernan	T	C	C	C	D	C	C	
Mariso	M	D	C	C	C	C	C	
Susy	C	C	C	M	M	C	D	
Diana	C	C	C	M	C	M	D	
Brayan	C	C	C	T	C	D	C	
Nallel	C	C	D	C	C	M	C	
Marlet	D	C	C	M	C	C	C	
Lucia	D	C	C	C	C	T	C	
Fabian	C	D	C	C	C	T	C	
Albert	C	M	M	C	C	C	D	
Elena	C	M	C	C	C	D	C	
Nancy	C	C	C	C	M	M	D	
Andrea	T	C	C	C	D	C	C	


In [8]:
for pR in np.arange(0.25, 1, 0.25):
    for pM in np.arange(0.25, 1, 0.25):
        s, iter = 0, 10
        tracker, best = [], -1e10
        for i in range(iter):
            r = genetic_algorithm(rules, (breaks, areas, inventario, people, domingos), popSize, 1000, pRep = pR, pMut = pM, dim = (len(people), 7, 0, len(breaks)), init = initial_population, debug = False)
            s += r['fitness']
            if not i or s > best:
                best = s
                tracker = r['bestTracker']
        graph(tracker)
        print("(pR = {}, pM = {})\t->\t{}".format(pR, pM, s/iter))