<a href="https://colab.research.google.com/github/LuisR-jpg/School/blob/master/Machine%20Learning%20I/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy tutorial

> NumPy is a Python library.
>
> NumPy is used for working with arrays.
>
> NumPy is short for "Numerical Python".

See the reference in [W3 Schools](https://www.w3schools.com/python/numpy/default.asp).

### NumPy Introduction

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists. This is achieved by storing data at one continuous place in memory unlike lists.
This library is written partially in Python, and the parts that require fast computation are written in C or C++.

### NumPy getting started

    import numpy as np
*In Python alias are an alternate name for referring to the same thing.*
    
    print(np.__version__)
*The version string is stored under \_\_version\_\_ attribute.*

### NumPy Creating Arrays

We can create a NumPy ***ndarray*** object by using the array() function.
To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray.

#### Dimension in Arrays
- 0-D Arrays are scalars
- 1-D Arrays are called uni-dimensional
- 2-D Arrays are used to represent matrix or 2nd order tensors
- 3-D Arrays has matrices as its elements and they're used to represent 3rd order tensor.

The ***ndim*** attribute is an integer that tells us how many dimensions the array has.

*When the array is created, you can define the number of dimensions by using the ndmin argument*

In [ ]:
import numpy as np

#Creating 
uno = np.array([1, 2, 3, 4, 5])
print(uno)
print(type(uno))
dos = np.array((1, 2, 3, 4, 5))

#Dimensions
zeroD = np.array(42)
oneD = np.array([1, 2, 3, 4, 5])
twoD = np.array([[1, 2, 3], [4, 5, 6]])
threeD = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
fiveD = np.array([1, 2, 3, 4], ndmin=5)
print(zeroD.ndim)
print(oneD.ndim)
print(twoD.ndim)
print(threeD.ndim)
print(fiveD.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
0
1
2
3
5


### NumPy Array Indexing
#### Access Array Elements
Array indexing is the same as accessing an array element.

To access elements from several arrays we can use comma separated integers representing the dimension and the index of the element.

#### Negative Indexing
Use negative indexing to access an array from the end.

In [ ]:
import numpy as np

oneD = np.array([1, 2, 3, 4])
twoD = np.array([[1,2,3,4,5], [6,7,8,9,10]])
threeD = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])


#Access
print(oneD[0])
print('2nd element on 1st row: ', twoD[0, 1])
print(threeD[0, 1, 2])

#Negative indexing
print('Last element from 2nd dim: ', twoD[1, -1])

1
2nd element on 1st row:  2
6
Last element from 2nd dim:  10


### NumPy Array Slicing
#### Slicing Arrays
Slicing in python means taking elements from one given index to another given index *[start, end)*.

- We pass slice instead of index like this: ***[start:end]***.

- We can also define the step, like this: ***[start:end:step]***.

*If we don't pass start its considered 0*

*If we don't pass end its considered length of array in that dimension*

*If we don't pass step its considered 1*

#### Negative Slicing
Use the minus operator to refer to an index from the end

#### Step
Determines step of the slicing

#### Slicing more dimensional arrays
Slicing can be applied to any dimension

In [ ]:
import numpy as np

oneD = np.array([1, 2, 3, 4, 5, 6, 7])
twoD = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

#Slicing arrays
print(oneD[1:5])
print('Slice elements from index 4 to the end of the array:', oneD[4:])
print('From [beginning to end)', oneD[:4])

#Negative slicing
print('Slice from the end [third element, last element)', arr[-3:-1])

#Step
print(oneD[1:5:2])
print(oneD[::2])

#Slicing 2-D
print(twoD[1, 1:4])
print(twoD[0:2, 2])
print(twoD[0:2, 1:4])

[2 3 4 5]
Slice elements from index 4 to the end of the array: [5 6 7]
From [beginning to end) [1 2 3 4]
Slice from the end [third element, last element) [5 6]
[2 4]
[1 3 5 7]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


### NumPy Data Types
#### Data types
##### Python
By default Python have these data types:

- strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
- integer - used to represent integer numbers. e.g. -1, -2, -3
- float - used to represent real numbers. e.g. 1.2, 42.42
- boolean - used to represent True or False.
- complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

##### NumPy
Below is a list of all data types in NumPy and the characters used to represent them.

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

#### Checking the Data Type of an Array
The NumPy array object has a property called ***dtype*** that returns the data type of the array

#### Creating Arrays With a Defined Data Type
Array() can take an optional argument that allows to define the expected data type of the array elements

*For i, u, f, S and U we can define size as well.*

#### What if a Value Can Not Be Converted?
Raises **ValueError**

#### Convert data type of existing array
The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

#Checking data type
print(arr.dtype)

#Creating arrays with defined data type
arr = np.array([1, 2, 3, 4], dtype='S')
arr = np.array([1, 2, 3, 4], dtype='i2') 
print(arr.dtype)

#What if a value can't be converted?
try:
  arr = np.array(['a', '2', '3'], dtype='i')
except ValueError:
  print("See? I'm here")

#Converting Data Type on Existing Arrays
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr, newarr.dtype)
newarr = arr.astype(int)
print(newarr, newarr.dtype)

int32
int16
See? I'm here
[1 2 3] int32
[1 2 3] int32


### The Difference Between Copy and View
- **Copy** is a duplicated of the array, it is independant from the original.
- **View** is a reference of the original, both are connected. But the view doesn't own the data.

#### Check if Array owns it's data
Every NumPy array has the attribute ***base*** that returns **None** if the array owns the data. Otherwise, the base  attribute **refers** to the original object.


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
copy = arr.copy()
view = arr.view()

#Check property
print(copy.base)
print(view.base)

None
[1 2 3 4 5]


### NumPy Array Shape
#### Shape of an array
Is the number of elements in each dimension.

#### Get the Shape of an Array
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.


In [ ]:
import numpy as np

twoD = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
fiveD = np.array([1, 2, 3, 4], ndmin=5)

print(twoD.shape)
print(fiveD.shape)

(2, 4)
(1, 1, 1, 1, 4)


### NumPy Array Reshaping
#### Reshaping Arrays
By reshaping we can add or remove dimensions or change number of elements in each dimension.
#### Can We Reshape Into any Shape?
Yes, as long as the elements required for reshaping are equal in both shapes.
#### Returns Copy or View?
Returns the original array, so it is a view.
#### Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.
#### Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

We can use ***reshape(-1)*** to do this.



In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print('1D to 2D', '\n', arr.reshape(4, 3))
print('1D to 3D', '\n', arr.reshape(2, 3, 2))

#Can We Reshape Into any Shape?
try:
  print(arr.reshape(3, 3))
except ValueError:
  print("See? I'm here")

#Returns a view or a copy?
print(arr.reshape(4, 3).base)

#Unknown dimension
print(arr.reshape(2, 2, -1))

#Flattening the arrays
print(arr.reshape(-1))

1D to 2D 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
1D to 3D 
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
See? I'm here
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


### NumPy Array Iterating
#### Iterating Arrays
As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a n-D array it will go through n-1th dimension one by one.
#### Iterating Arrays Using nditer()
The function ***nditer()*** is a function that solves some basic issues which we face in iteration.
##### Iterating on Each Scalar Element
    for x in np.nditer(arr):
      print(x)
##### Iterating Array With Different Data Types
We can use ***op_dtypes*** argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place so it needs ***flags=['buffered']***.
##### Iterating With Different Step Size
We can use filtering and followed by iteration.
#### Enumerated Iteration Using ndenumerate()
Sometimes we require corresponding index of the element while iterating, the ***ndenumerate()*** method can be used for those usecases.

In [13]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

#Iterating arrays
for x in arr:
  print(x)
for x in arr:
  for y in x:
    for z in y:
      print(z)
    
##nditer()
#Iterating on Each Scalar Element
for x in np.nditer(arr):
  print(x)
#Iterating Array With Different Data Types
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)
#Iterating With Different Step Size
for x in np.nditer(arr[:, :, ::2]):
  print(x)

#Enumerated Iteration Using ndenumerate(
for idx, x in np.ndenumerate(arr):
  print(idx, x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12
b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'
1
3
4
6
7
9
10
12
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


### Joining NumPy Arrays 
Joining means putting contents of two or more arrays in a single array.

We pass a sequence of arrays that we want to join to the ***concatenate()*** function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [8]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis = 1)
print(arr)

[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]
